version: '2'
services:
  db:
    image: postgres
    ports:
          - 5433:5432
  web:
    build: .
    command: bundle exec rackup -p 9292 -o 0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - "9292:9292"
    depends_on:
      - db